apiVersion: devices.kubeedge.io/v1beta1
kind: Device
metadata:
  name: iot-door-access-001
  namespace: default
  annotations:
    description: "门禁设备实例，对应 11-door-access-simulator 模拟器"
spec:
  deviceModelRef:
    name: iot-door-access-model
  nodeName: cloudedge-edge-02
  protocol:
    protocolName: mqttIot
    configData:
      mqttBroker: "tcp://192.168.122.212:1884"
      deviceId: "door-access-001"
      mqttUsername: ""
      mqttPassword: ""
      mqttClientId: "mapper-door-access-001"

  properties:
    - name: taskControl
      visitors:
        configData:
          fieldName: taskControl
      collectCycle: 10000
      reportToCloud: true
      desired:
        value: "1"

    - name: door1Control1
      visitors:
        configData:
          fieldName: door1Control1
      collectCycle: 5000
      reportToCloud: true
      desired:
        value: "0"   # 默认关门

    - name: door1Control2
      visitors:
        configData:
          fieldName: door1Control2
      collectCycle: 5000
      reportToCloud: true
      desired:
        value: "0"

    - name: door1OperateTime1
      visitors:
        configData:
          fieldName: door1OperateTime1
      collectCycle: 5000
      reportToCloud: true

    - name: door1OperateTime2
      visitors:
        configData:
          fieldName: door1OperateTime2
      collectCycle: 5000
      reportToCloud: true
